import globalvars as gv
import helper


 
HB_REQUESTS = {
    "HOMEBRIDGE_LOGIN"                : "HOMEBRIDGE_LOGIN:              NAME={}, PASSWORD={}, DEVICE_TYPE={}",
    "HOMEBRIDGE_REGISTER"             : "HOMEBRIDGE_REGISTER:           NAME={}, PASSWORD={}, DOMAIN={}, EMAIL={}, TOKEN={}",
    "HOMEBRIDGE_CHANGE_PASSWORD"      : "HOMEBRIDGE_CHANGE_PASSWORD:    NAME={}, PASSWORD={}, NEWPASSWORD={}",
    "HOMEBRIDGE_UPDATE_DATA"          : "HOMEBRIDGE_UPDATE_DATA:        NAME={}, PASSWORD={}, IP={}, DATA={}",
    "HOMEBRIDGE_UPDATE_ACCOUNT"       : "HOMEBRIDGE_UPDATE_ACCOUNT:     NAME={}, PASSWORD={}, FIRST_NAME={}, LAST_NAME={}, EMAIL={}",
    "HOMEBRIDGE_REQUEST_RELAY_LIST"   : "HOMEBRIDGE_REQUEST_RELAY_LIST: NAME={}, PASSWORD={}",
    "HOMEBRIDGE_DELETE"               : "HOMEBRIDGE_DELETE:             NAME={}, PASSWORD={}",
    "HOMEBRIDGE_FORGOT_PASSWORD"      : "HOMEBRIDGE_FORGOT_PASSWORD:    NAME={}",
    "HOMEBRIDGE_FIND"                 : "HOMEBRIDGE_FIND:               NAME={}",
}


H = "HELLLLOOO"
